import imge_one from "../../Assets/Images/pic1.jpg";
import imge_two from "../../Assets/Images/pic2.jpg";
import imge_three from "../../Assets/Images/pic555.jpg";
import imge_four from "../../Assets/Images/pic666.jpg";
import imge_five from "../../Assets/Images/pic777.jpg";
import imge_six from "../../Assets/Images/pic888.jpg";


import india from '../../Assets/icon/india.png';
import canada from '../../Assets/icon/canada.png';
import russia from '../../Assets/icon/russia.png';
import uk from '../../Assets/icon/uk.png';
import aus from '../../Assets/icon/aus.png';
import us from '../../Assets/icon/usa.png';
import pak from '../../Assets/icon/pak.png';
import ger from '../../Assets/icon/germany.png';
import uae from '../../Assets/icon/uae.png';
import china from '../../Assets/icon/china.png';


import best_one from "../../Assets/Images/d1.jpg";
import best_two from "../../Assets/Images/d2.jpg";
import best_three from "../../Assets/Images/d3.jpg";
import best_four from "../../Assets/Images/d4.jpg";
import best_five from "../../Assets/Images/d5.jpg";
import best_six from "../../Assets/Images/d6.jpg";
import best_seven from "../../Assets/Images/d7.jpg";

import best_one1 from "../../Assets/Images/pic3.jpg";
import best_one2 from "../../Assets/Images/pic2.jpg";



export const TableData = [
    {
      name: "Batman",
      proj_lead_img: imge_one,
      proj_name: "Liam Risher",
      progress: "53%",
      progress_color: "#0d99ff",
      assign_imgone: imge_one,
      assign_imgtwo: imge_three,
      assign_imgthree: imge_four,
      status: "Inprogress",
      border: "1px solid red",
      width: "53%",
      border1: "50%",
      date: "08 Sep 2023",
      status_bg: "#0d99ff1a",
      status_color: "#0d99ff", 
    },
    {
        name: "Mivy App",
        proj_lead_img: imge_one,
        proj_name: "Liam Risher",
        progress: "52%",
        width: "52%",
        progress_color: "#0d99ff",
        assign_imgone: imge_one,
        assign_imgtwo: imge_five,
        assign_imgthree: imge_four,
        status: "Inprogress",
        date: "06 Sep 2021",
        status_bg: "#ffdede",
        status_color: "#FF5E5E", 
      },
      {
        name: "Crypto App",
        proj_lead_img: imge_two,
        proj_name: "Ankites Risher",
        progress: "58%",
        width: "58%",
        progress_color: "#0d99ff",
        assign_imgone: imge_one,
        assign_imgtwo: imge_six,
        status: "Pending",
        date: "06 Sep 2021",
        status_bg: "#ffdede",
        status_color: "#FF5E5E", 
      },
      {
        name: "Bender Project",
        proj_lead_img: imge_two,
        proj_name: "Oliver Noah",
        progress: "30%",
        width: "30%",
        progress_color: "#FF5E5E",
        assign_imgone: imge_one,
        assign_imgtwo: imge_three,
        assign_imgthree: imge_four,
        status: "Pending",
        date: "06 Sep 2021",
        status_bg: "#ffdede",
        status_color: "#FF5E5E", 
      },
      {
        name: "Canary",
        proj_lead_img: imge_six,
        proj_name: "Elijah James",
        progress: "40%",
        width: "40%",
        progress_color: "#3AC977",
        assign_imgone: imge_four,
        assign_imgtwo: imge_three,
        assign_imgthree: imge_one,
        assign_imgfour: imge_four,
        status: "Inprogress",
        date: "06 Sep 2021",
        status_bg: "#daf5e6",
        status_color: "#3AC977", 
      },
      {
        name: "Casanova",
        proj_lead_img: imge_one,
        proj_name: "Liam Risher",
        progress: "53%",
        width: "10%",
        progress_color: "#0d99ff",
        assign_imgone: imge_one,
        assign_imgtwo: imge_three,
        assign_imgthree: imge_four,
        status: "Inprogress",
        date: "08 Sep 2023",
        status_bg: "#0d99ff1a",
        status_color: "#0d99ff", 
      },
      {
        name: "Bender Project",
        proj_lead_img: imge_two,
        proj_name: "Oliver Noah",
        progress: "30%",
        width: "30%",
        progress_color: "#0d99ff",
        assign_imgone: imge_one,
        assign_imgtwo: imge_three,
        assign_imgthree: imge_four,
        status: "Pendindg",
        date: "06 Sep 2021",
        status_bg: "#ffdede",
        status_color: "#FF5E5E", 
      },
      {
        name: "Canary",
        proj_lead_img: imge_two,
        proj_name: "Elijah James",
        progress: "40%",
        width: "40%",
        progress_color: "#3AC977",
        assign_imgone: imge_four,
        assign_imgtwo: imge_three,
        assign_imgthree: imge_one,
        assign_imgfour: imge_four,
        status: "Inprogress",
        date: "06 Sep 2021",
        status_bg: "#daf5e6",
        status_color: "#3AC977", 
      },
      {
        name: "Casanova",
        proj_lead_img: imge_one,
        proj_name: "William Risher",
        progress: "53%",
        width: "60%",
        progress_color: "#0d99ff",
        assign_imgone: imge_one,
        assign_imgtwo: imge_three,
        assign_imgthree: imge_four,
        status: "Inprogress",
        date: "08 Sep 2023",
        status_bg: "#0d99ff1a",
        status_color: "#0d99ff", 
      },
      {
        name: "Bigfish",
        proj_lead_img: imge_five,
        proj_name: "Donald Benjamin",
        progress: "30%",
        width: "30%",
        progress_color: "#0d99ff",
        assign_imgone: imge_one,
        assign_imgtwo: imge_five,
        assign_imgthree: imge_four,
        status: "Inprogress",
        date: "06 Sep 2021",
        status_bg: "#ffdede",
        status_color: "#FF5E5E", 
      },
  ];


  export const Maprecord = [
    {
      country: india,
      title: "India",
      range: "50%",
    },
    {
      country: canada,
      title: "Canada",
      range: "30%",
    },
    {
      country: russia,
      title: "Russia",
      range: "20%",
    },
    {
      country: uk,
      title: "United Kingdom",
      range: "40%",
    },
    {
      country: aus,
      title: "Australia",
      range: "60%",
    },
    {
      country: us,
      title: "United States",
      range: "20%",
    },
    {
      country: pak,
      title: "Pakistan",
      range: "20%",
    },
    {
      country: ger,
      title: "Germany",
      range: "80%",
    },
    {
      country: uae,
      title: "UAE",
      range: "30%",
    },
    {
      country: china,
      title: "China",
      range: "40%",
    },
  ];


export const Bestsellingproduct = [
  {
    image: best_one,
    title: "lether Dress",
    date: "24 Apr 2021",
    price: "$85.20",
    order:"750",
    stock: "Out of Stock",
    amount: "$1200.75",
    bg_color: "#ffdede",
    text_color: "#ff5e5e",
  },
  {
    image: best_two,
    title: "Men Jacket",
    date: "24 Apr 2021",
    price: "$85.20",
    order:"750",
    stock: "Out of Stock",
    amount: "$1200.75",
    bg_color: "#ffdede",
    text_color: "#ff5e5e",
  },
  {
    image: best_three,
    title: "lether Dress",
    date: "24 Apr 2021",
    price: "$85.20",
    order:"750",
    stock: "Out of Stock",
    amount: "$1200.75",
    bg_color: "#ffdede",
    text_color: "#ff5e5e",
  },
  {
    image: best_four,
    title: "Boy Dress",
    date: "24 Apr 2021",
    price: "$85.20",
    order:"750",
    stock: "In Stock",
    amount: "$1200.75",
    bg_color: "#daf5e6",
    text_color: "#3AC977",
  },
  {
    image: best_five,
    title: "Teen Dress",
    date: "24 Apr 2021",
    price: "$85.20",
    order:"750",
    stock: "Out of Stock",
    amount: "$1200.75",
    bg_color: "#daf5e6",
    text_color: "#3AC977",
  },
  {
    image: best_six,
    title: "White Top Dress",
    date: "24 Apr 2021",
    price: "$85.20",
    order:"750",
    stock: "Out of Stock",
    amount: "$1200.75",
    bg_color: "#daf5e6",
    text_color: "#3AC977",
  },
  {
    image: best_seven,
    title: "Mobile",
    date: "24 Apr 2021",
    price: "$85.20",
    order:"750",
    stock: "Out of Stock",
    amount: "$1200.75",
    bg_color: "#ffdede",
    text_color: "#ff5e5e",
  },
];


export const Employee = [
  {
    id: "1001",
    image: best_one,
    title: "Ricky Antony",
    job: "Web Designer",
    email: "xyz@gmail.com",
    contact:"+12 123 456 7890",
    gender: "Female",
    location: "AZ",
    status: "Active",
    text_color: "#3AC977",
    bg_color: "#daf5e6",
  },
  {
    id: "1002",
    image: best_one,
    title: "Ricky Antony",
    job: "Web Designer",
    email: "xyz@gmail.com",
    contact:"+12 123 456 7890",
    gender: "Female",
    location: "Delhi",
    status: "Pending",
    text_color: "#FF5E5E",
    bg_color: "#ffdede",
  },
  {
    id: "1003",
    image: best_one1,
    title: "Ricky Antony",
    job: "Web Designer",
    email: "xyz@gmail.com",
    contact:"+12 123 456 7890",
    gender: "Male",
    location: "Delhi",
    status: "Active",
    text_color: "#3AC977",
    bg_color: "#daf5e6",
  },
  {
    id: "1004",
    image: best_one,
    title: "Ricky Antony",
    job: "Web Designer",
    email: "xyz@gmail.com",
    contact:"+12 123 456 7890",
    gender: "Female",
    location: "USA",
    status: "Pending",
    text_color: "#FF5E5E",
    bg_color: "#ffdede",
  },
  {
    id: "1005",
    image: best_one1,
    title: "Ricky Antony",
    job: "Web Designer",
    email: "xyz@gmail.com",
    contact:"+12 123 456 7890",
    gender: "Male",
    location: "Delhi",
    status: "Active",
    text_color: "#3AC977",
    bg_color: "#daf5e6",
  },
  {
    id: "1006",
    image: best_one2,
    title: "Ricky Antony",
    job: "Web Designer",
    email: "xyz@gmail.com",
    contact:"+12 123 456 7890",
    gender: "Male",
    location: "USA",
    status: "Pending",
    text_color: "#FF5E5E",
    bg_color: "#ffdede",
  },
  {
    id: "1007",
    image: best_one1,
    title: "Tony Antony",
    job: "Web Designer",
    email: "xyz@gmail.com",
    contact:"+12 123 456 7890",
    gender: "Male",
    location: "NYC",
    status: "Active",
    text_color: "#3AC977",
    bg_color: "#daf5e6",
  },{
    id: "1008",
    image: best_one1,
    title: "Ricky M",
    job: "Software Designer",
    email: "xyz@gmail.com",
    contact:"+12 123 456 7890",
    gender: "Male",
    location: "PA",
    status: "Active",
    text_color: "#3AC977",
    bg_color: "#daf5e6",
  },
  {
    id: "1009",
    image: best_one2,
    title: "Mony Antony",
    job: "Web Designer",
    email: "xyz@gmail.com",
    contact:"+12 123 456 7890",
    gender: "Male",
    location: "WA",
    status: "Active",
    text_color: "#3AC977",
    bg_color: "#daf5e6",
  },
  {
    id: "1010",
    image: best_one2,
    title: "Honey Risher",
    job: "Web Designer",
    email: "xyz@gmail.com",
    contact:"+12 123 456 7890",
    gender: "Male",
    location: "WA",
    status: "Active",
    text_color: "#3AC977",
    bg_color: "#daf5e6",
  },
]